/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2024-12-16 21:22:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class messages_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>SUNRISE HOTEL - News Letters</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- CSS intégré -->\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Roboto', sans-serif;\r\n");
      out.write("            background-color: #f7f7f7;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #wrapper {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: row;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            background-color: #f7f7f7;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Navbar */\r\n");
      out.write("        .navbar {\r\n");
      out.write("            background-color: #2196F3;\r\n");
      out.write("            color: white;\r\n");
      out.write("            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar a {\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar-brand {\r\n");
      out.write("            font-size: 24px;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            letter-spacing: 1px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Sidebar */\r\n");
      out.write("        .navbar-side {\r\n");
      out.write("            background-color: #333;\r\n");
      out.write("            color: white;\r\n");
      out.write("            width: 250px;\r\n");
      out.write("            padding-top: 20px;\r\n");
      out.write("            box-shadow: 4px 0 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar-side ul {\r\n");
      out.write("            list-style-type: none;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar-side ul li a {\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            display: block;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar-side ul li a:hover {\r\n");
      out.write("            background-color: #575757;\r\n");
      out.write("            transition: background-color 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Main Content Area */\r\n");
      out.write("        #page-wrapper {\r\n");
      out.write("            flex-grow: 1;\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .table-responsive {\r\n");
      out.write("            margin-top: 30px;\r\n");
      out.write("            overflow-x: auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .table {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .table th, .table td {\r\n");
      out.write("            padding: 12px 15px;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            border-bottom: 1px solid #ddd;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .table th {\r\n");
      out.write("            background-color: #2196F3;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .table-striped tbody tr:nth-child(odd) {\r\n");
      out.write("            background-color: #f9f9f9;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .table-hover tbody tr:hover {\r\n");
      out.write("            background-color: #f1f1f1;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn {\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            background-color: #2196F3;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            transition: background-color 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-approve {\r\n");
      out.write("            background-color: #4CAF50;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-reject {\r\n");
      out.write("            background-color: #f44336;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn:hover {\r\n");
      out.write("            opacity: 0.8;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-box {\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            border: 1px solid #ddd;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 300px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .page-header {\r\n");
      out.write("            font-size: 36px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("        <nav class=\"navbar-default navbar-side\" role=\"navigation\">\r\n");
      out.write("            <div class=\"sidebar-collapse\">\r\n");
      out.write("                <ul class=\"nav\" id=\"main-menu\">\r\n");
      out.write("                    <li><a href=\"home.jsp\"><i class=\"fa fa-dashboard\"></i> Status</a></li>\r\n");
      out.write("                    <li><a href=\"messages.jsp\" class=\"active-menu\"><i class=\"fa fa-desktop\"></i> News Letters</a></li>\r\n");
      out.write("                    <li><a href=\"roombook.jsp\"><i class=\"fa fa-bar-chart-o\"></i> Room Booking</a></li>\r\n");
      out.write("                    <li><a href=\"payment.jsp\"><i class=\"fa fa-qrcode\"></i> Payment</a></li>\r\n");
      out.write("                    <li><a href=\"profit.jsp\"><i class=\"fa fa-qrcode\"></i> Profit</a></li>\r\n");
      out.write("                    <li><a href=\"logout.jsp\"><i class=\"fa fa-sign-out fa-fw\"></i> Logout</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"page-wrapper\">\r\n");
      out.write("            <div id=\"page-inner\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-12\">\r\n");
      out.write("                        <h1 class=\"page-header\">News Letters Management</h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Search Box -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-6\">\r\n");
      out.write("                        <input type=\"text\" class=\"search-box\" placeholder=\"Search News Letters...\" onkeyup=\"searchNewsLetters()\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-12\">\r\n");
      out.write("                        <div class=\"panel panel-default\">\r\n");
      out.write("                            <div class=\"panel-body\">\r\n");
      out.write("                                <div class=\"table-responsive\">\r\n");
      out.write("                                    <table class=\"table table-striped table-bordered table-hover\" id=\"dataTables-example\">\r\n");
      out.write("                                        <thead>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <th>ID</th>\r\n");
      out.write("                                                <th>Name</th>\r\n");
      out.write("                                                <th>Email</th>\r\n");
      out.write("                                                <th>Subject</th>\r\n");
      out.write("                                                <th>Message</th>\r\n");
      out.write("                                                <th>Status</th>\r\n");
      out.write("                                                <th>Actions</th>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        </thead>\r\n");
      out.write("                                        <tbody>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td>1</td>\r\n");
      out.write("                                                <td>John Doe</td>\r\n");
      out.write("                                                <td>john.doe@example.com</td>\r\n");
      out.write("                                                <td>Hotel Services</td>\r\n");
      out.write("                                                <td>Interested in newsletter</td>\r\n");
      out.write("                                                <td>Not Allowed</td>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                    <button class=\"btn btn-approve\" onclick=\"approveNewsletter(1)\">Approve</button>\r\n");
      out.write("                                                    <button class=\"btn btn-reject\" onclick=\"rejectNewsletter(1)\">Reject</button>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td>2</td>\r\n");
      out.write("                                                <td>Jane Smith</td>\r\n");
      out.write("                                                <td>jane.smith@example.com</td>\r\n");
      out.write("                                                <td>Special Offers</td>\r\n");
      out.write("                                                <td>Want to receive updates</td>\r\n");
      out.write("                                                <td>Allowed</td>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                    <button class=\"btn btn-reject\" onclick=\"rejectNewsletter(2)\">Revoke</button>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        </tbody>\r\n");
      out.write("                                    </table>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function searchNewsLetters() {\r\n");
      out.write("            var input, filter, table, tr, td, i, txtValue;\r\n");
      out.write("            input = document.querySelector(\".search-box\");\r\n");
      out.write("            filter = input.value.toUpperCase();\r\n");
      out.write("            table = document.querySelector(\".table\");\r\n");
      out.write("            tr = table.getElementsByTagName(\"tr\");\r\n");
      out.write("\r\n");
      out.write("            for (i = 0; i < tr.length; i++) {\r\n");
      out.write("                td = tr[i].getElementsByTagName(\"td\");\r\n");
      out.write("                for (var j = 0; j < td.length; j++) {\r\n");
      out.write("                    if (td[j]) {\r\n");
      out.write("                        txtValue = td[j].textContent || td[j].innerText;\r\n");
      out.write("                        if (txtValue.toUpperCase().indexOf(filter) > -1) {\r\n");
      out.write("                            tr[i].style.display = \"\";\r\n");
      out.write("                            break;\r\n");
      out.write("                        } else {\r\n");
      out.write("                            tr[i].style.display = \"none\";\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function approveNewsletter(id) {\r\n");
      out.write("            alert('Newsletter ' + id + ' approved');\r\n");
      out.write("            // In a real application, this would call a server-side script\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function rejectNewsletter(id) {\r\n");
      out.write("            alert('Newsletter ' + id + ' rejected');\r\n");
      out.write("            // In a real application, this would call a server-side script\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
