/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2024-12-17 00:30:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.*;
import java.sql.*;

public final class roombook_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


	String curdate,title,fname,lname,email,nat,country,phone,troom,bed,meal,cin,cout,sta;
	int nroom,days;
	PreparedStatement ps;
	ResultSet rs;
	public static String getDate()
	{
		DateFormat df=new SimpleDateFormat("yyyy-MMM-dd");
		String date=df.format(new java.util.Date());
		return date;
	}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

	Connection c=(Connection)application.getAttribute("connection");
	String user=(String)session.getAttribute("user");
	String rid1=request.getParameter("rid");
	int id=0;
		if(rid1==null)
		{
				
			response.sendRedirect("home.jsp");
		}
		else {
				curdate=getDate();

				id =Integer.parseInt(rid1);
				
				
				String q ="Select * from roombook where id = ?";			
				ps=c.prepareStatement(q,ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
				ps.setInt(1,id);
				ResultSet rs=ps.executeQuery();				
				while(rs.next())
				{
					title = rs.getString("title");
					fname = rs.getString("fname");
					lname = rs.getString("lname");
					email = rs.getString("email");
					nat = rs.getString("national");
					country = rs.getString("country");
					phone = rs.getString("phone");
					troom = rs.getString("troom");
					nroom = Integer.parseInt(rs.getString("nroom"));
					bed = rs.getString("bed");
					//String non = rs.getString("nroom");
					meal = rs.getString("meal");
					cin = rs.getString("cin");
					cout = rs.getString("cout");
					sta = rs.getString("stat");
					days = rs.getInt("nodays");							
				
				}					
	}						
	
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>Administrator	</title>\r\n");
      out.write("    <!-- Bootstrap Styles-->\r\n");
      out.write("    <link href=\"assets/css/bootstrap.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <!-- FontAwesome Styles-->\r\n");
      out.write("    <link href=\"assets/css/font-awesome.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <!-- Morris Chart Styles-->\r\n");
      out.write("    <link href=\"assets/js/morris/morris-0.4.3.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <!-- Custom Styles-->\r\n");
      out.write("    <link href=\"assets/css/custom-styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <!-- Google Fonts-->\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("        <nav class=\"navbar navbar-default top-navbar\" role=\"navigation\">\r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".sidebar-collapse\">\r\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"home.jsp\"> ");
      out.print(user);
      out.write(" </a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"nav navbar-top-links navbar-right\">\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                    <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\" aria-expanded=\"false\">\r\n");
      out.write("                        <i class=\"fa fa-user fa-fw\"></i> <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-user\">\r\n");
      out.write("                        <li><a href=\"usersetting.jsp\"><i class=\"fa fa-user fa-fw\"></i> User Profile</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"settings.jsp\"><i class=\"fa fa-gear fa-fw\"></i> Settings</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li><a href=\"logout.jsp\"><i class=\"fa fa-sign-out fa-fw\"></i> Logout</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <!-- /.dropdown-user -->\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- /.dropdown -->\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <!--/. NAV TOP  -->\r\n");
      out.write("        <nav class=\"navbar-default navbar-side\" role=\"navigation\">\r\n");
      out.write("            <div class=\"sidebar-collapse\">\r\n");
      out.write("                <ul class=\"nav\" id=\"main-menu\">\r\n");
      out.write("\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a  href=\"home.jsp\"><i class=\"fa fa-dashboard\"></i> Status</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"messages.jsp\"><i class=\"fa fa-desktop\"></i> News Letters</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("					<li>\r\n");
      out.write("                        <a class=\"active-menu\" href=\"roombook.jsp\"><i class=\"fa fa-bar-chart-o\"></i> Room Booking</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"payment.jsp\"><i class=\"fa fa-qrcode\"></i> Payment</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("					<li>\r\n");
      out.write("                        <a  href=\"profit.jsp\"><i class=\"fa fa-qrcode\"></i> Profit</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"logout.jsp\"><i class=\"fa fa-sign-out fa-fw\"></i> Logout</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("					</ul>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </nav>\r\n");
      out.write("        <!-- /. NAV SIDE  -->\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("        <div id=\"page-wrapper\">\r\n");
      out.write("            <div id=\"page-inner\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-12\">\r\n");
      out.write("                        <h1 class=\"page-header\">\r\n");
      out.write("                            Room Booking<small>	");
      out.print(curdate);
      out.write(" </small>\r\n");
      out.write("                        </h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"col-md-8 col-sm-8\">\r\n");
      out.write("                    <div class=\"panel panel-info\">\r\n");
      out.write("                        <div class=\"panel-heading\">\r\n");
      out.write("                           Booking Confirmation\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"panel-body\">\r\n");
      out.write("							\r\n");
      out.write("							<div class=\"table-responsive\">\r\n");
      out.write("                                <table class=\"table\">\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                            <th>DESCRIPTION</th>\r\n");
      out.write("                                            <th>INFORMATION</th>\r\n");
      out.write("                                            \r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <th>Name</th>\r\n");
      out.write("                                            <th>");
      out.print(title);
      out.write(' ');
      out.print(fname);
      out.write(' ');
      out.print(lname);
      out.write("</th>\r\n");
      out.write("                                            \r\n");
      out.write("                                        </tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("                                            <th>Email</th>\r\n");
      out.write("                                            <th>");
      out.print(email);
      out.write(" </th>\r\n");
      out.write("                                            \r\n");
      out.write("                                        </tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("                                            <th>Nationality </th>\r\n");
      out.write("                                            <th>");
      out.print(nat);
      out.write("</th>\r\n");
      out.write("                                            \r\n");
      out.write("                                        </tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("                                            <th>Country </th>\r\n");
      out.write("                                            <th>");
      out.print(country);
      out.write("</th>\r\n");
      out.write("                                            \r\n");
      out.write("                                        </tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("                                            <th>Phone No </th>\r\n");
      out.write("                                            <th>");
      out.print(phone);
      out.write("</th>\r\n");
      out.write("                                            \r\n");
      out.write("                                        </tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("                                            <th>Type Of the Room </th>\r\n");
      out.write("                                            <th>");
      out.print(troom);
      out.write("</th>\r\n");
      out.write("                                            \r\n");
      out.write("                                        </tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("                                            <th>No Of the Room </th>\r\n");
      out.write("                                            <th>");
      out.print(nroom);
      out.write("</th>\r\n");
      out.write("                                            \r\n");
      out.write("                                        </tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("                                            <th>Meal Plan </th>\r\n");
      out.write("                                            <th>");
      out.print(meal);
      out.write("</th>\r\n");
      out.write("                                            \r\n");
      out.write("                                        </tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("                                            <th>Bedding </th>\r\n");
      out.write("                                            <th>");
      out.print(bed);
      out.write("</th>\r\n");
      out.write("                                            \r\n");
      out.write("                                        </tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("                                            <th>Check-in Date </th>\r\n");
      out.write("                                            <th>");
      out.print(cin);
      out.write("</th>\r\n");
      out.write("                                            \r\n");
      out.write("                                        </tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("                                            <th>Check-out Date</th>\r\n");
      out.write("                                            <th>");
      out.print(cout);
      out.write("</th>\r\n");
      out.write("                                            \r\n");
      out.write("                                        </tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("                                            <th>No of days</th>\r\n");
      out.write("                                            <th>");
      out.print(days);
      out.write("</th>\r\n");
      out.write("                                            \r\n");
      out.write("                                        </tr>\r\n");
      out.write("										<tr>\r\n");
      out.write("                                            <th>Status Level</th>\r\n");
      out.write("                                            <th>");
      out.print(sta);
      out.write("</th>\r\n");
      out.write("                                            \r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                   \r\n");
      out.write("                                  \r\n");
      out.write("                                        \r\n");
      out.write("                                        \r\n");
      out.write("                                    \r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        \r\n");
      out.write("					\r\n");
      out.write("							\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"panel-footer\">\r\n");
      out.write("                            <form method=\"post\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("														<label>Select the Confirmation</label>\r\n");
      out.write("														<select name=\"conf\"class=\"form-control\">\r\n");
      out.write("															<option value selected>	</option>\r\n");
      out.write("															<option value=\"Confirm\">Confirm</option>\r\n");
      out.write("															\r\n");
      out.write("															\r\n");
      out.write("														</select>\r\n");
      out.write("										 </div>\r\n");
      out.write("							<input type=\"submit\" name=\"co\" value=\"Confirm\" class=\"btn btn-success\">\r\n");
      out.write("							\r\n");
      out.write("							</form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("			");

				String rsql ="select * from room";
				ps=c.prepareStatement(rsql,ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
				rs=ps.executeQuery();	
				int r =0 ;
				int sc =0;
				int gh = 0;
				int sr = 0;
				int dr = 0;
						while(rs.next())
						{
							r = r + 1;
							String s = rs.getString("type");
							String p = rs.getString("place");
							if(s.equals("Superior Room") )
							{
								sc = sc+ 1;
							}
							
							if(s.equals("Guest House"))
							{
								gh = gh + 1;
							}
							if(s.equals("Single Room") )
							{
								sr = sr + 1;
							}
							if(s.equals("Deluxe Room") )
							{
								dr = dr + 1;
							}
							
						
						}
			
      out.write("\r\n");
      out.write("						\r\n");
      out.write("			");

				String csql ="select * from payment";
				ps=c.prepareStatement(csql,ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
				rs=ps.executeQuery();
				int cr =0 ;
				int csc =0;
				int cgh = 0;
				int csr = 0;
				int cdr = 0;
						while(rs.next())
						{
							cr =cr + 1;
							String cs = rs.getString("troom");
							
							if(cs.equals("Superior Room" ))
							{
								csc = csc + 1;
							}
							
							if(cs.equals("Guest House") )
							{
								cgh = cgh + 1;
							}
							if(cs.equals("Single Room") )
							{
								csr = csr + 1;
							}
							if(cs.equals("Deluxe Room") )
							{
								cdr = cdr + 1;
							}
							
						
						}
				
					
      out.write("\r\n");
      out.write("					<div class=\"col-md-4 col-sm-4\">\r\n");
      out.write("                    <div class=\"panel panel-default\">\r\n");
      out.write("                        <div class=\"panel-heading\">\r\n");
      out.write("                           Available Room Details\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"panel-body\">\r\n");
      out.write("						<table width=\"200px\">\r\n");
      out.write("							\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td><b>Superior Room	 </b></td>\r\n");
      out.write("								<td><button type=\"button\" class=\"btn btn-primary btn-circle\">\r\n");
      out.write("							");
  
									int f1 =sc - csc;
									if(f1 <=0 )
									{	
										out.print("NO");
									}
									else{
											out.print(f1);
									}
								
								
								
      out.write(" </button></td> \r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td><b>Guest House</b>	 </td>\r\n");
      out.write("								<td><button type=\"button\" class=\"btn btn-primary btn-circle\">\r\n");
      out.write("							");
 
								int f2 =  gh -cgh;
								if(f2 <=0 )
									{	
										out.print("NO");
									}
									else{
											out.print(f2);
									}

								
      out.write(" </button></td> \r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td><b>Single Room	 </b></td>\r\n");
      out.write("								<td><button type=\"button\" class=\"btn btn-primary btn-circle\">\r\n");
      out.write("							");

								int f3 =sr - csr;
								if(f3 <=0 )
									{	
										out.print("NO");
									}
									else{
											out.print(f3);
									}

								
      out.write(" </button></td> \r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td><b>Deluxe Room</b>	 </td>\r\n");
      out.write("								<td><button type=\"button\" class=\"btn btn-primary btn-circle\">\r\n");
      out.write("							");
 
								
								int f4 =dr - cdr; 
								if(f4 <=0 )
									{	
										out.print("NO");
									}
									else{
											out.print(f4);
									}
							
      out.write(" </button></td> \r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td><b>Total Rooms	</b> </td>\r\n");
      out.write("								<td> <button type=\"button\" class=\"btn btn-danger btn-circle\">\r\n");
      out.write("							");
 
								
								int f5 =r-cr; 
								if(f5 <=0 )
									{	
										out.print("NO");
									}
									else{
											out.print(f5);
									}
							
      out.write(" </button></td> \r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("                        \r\n");
      out.write("						\r\n");
      out.write("						</div>\r\n");
      out.write("                        <div class=\"panel-footer\">\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("					</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /. ROW  -->\r\n");
      out.write("				\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /. ROW  -->\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("         </div>\r\n");
      out.write("            <!-- /. PAGE INNER  -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /. PAGE WRAPPER  -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /. WRAPPER  -->\r\n");
      out.write("    <!-- JS Scripts-->\r\n");
      out.write("    <!-- jQuery Js -->\r\n");
      out.write("    <script src=\"assets/js/jquery-1.10.2.js\"></script>\r\n");
      out.write("    <!-- Bootstrap Js -->\r\n");
      out.write("    <script src=\"assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- Metis Menu Js -->\r\n");
      out.write("    <script src=\"assets/js/jquery.metisMenu.js\"></script>\r\n");
      out.write("    <!-- Morris Chart Js -->\r\n");
      out.write("    <script src=\"assets/js/morris/raphael-2.1.0.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/morris/morris.js\"></script>\r\n");
      out.write("    <!-- Custom Js -->\r\n");
      out.write("    <script src=\"assets/js/custom-scripts.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");

						if(request.getParameter("co")!=null)
						{	
							String st = request.getParameter("conf");
							
							 
							
							if(st.equals("Confirm"))
							{
									String urb = "UPDATE roombook SET stat='"+st+"' WHERE id = "+id;
									
								if(f1<=0)
								{
      out.write("\r\n");
      out.write("									<script type='text/javascript'> alert('Sorry! Not Available Superior Room ')</script>\r\n");
      out.write("								");
}
								else if(f2<=0)
									{
      out.write("\r\n");
      out.write("										<script type='text/javascript'> alert('Sorry! Not Available Guest House')</script>\r\n");
      out.write("										\r\n");
      out.write("									");
}
									else if (f3 <= 0)
									{
      out.write("\r\n");
      out.write("										<script type='text/javascript'> alert('Sorry! Not Available Single Room')</script>\r\n");
      out.write("									");
}
										else if(f4<=0)
										{
      out.write("\r\n");
      out.write("											<script type='text/javascript'> alert('Sorry! Not Available Deluxe Room')</script>\r\n");
      out.write("										");
}
										
										else
											{	
										ps=c.prepareStatement(urb);
										int i=ps.executeUpdate();
												// "<script type='text/javascript'> alert('Guest Room booking is confirm')</script>";
												// "<script type='text/javascript'> window.location='home.jsp'</script>";
												 double type_of_room = 0;       
														if(troom.equals("Superior Room"))
														{
															type_of_room = 320;
														
														}
														else if(troom.equalsIgnoreCase("Deluxe Room"))
														{
															type_of_room = 220;
														}
														else if(troom.equalsIgnoreCase("Guest House"))
														{
															type_of_room = 180;
														}
														else if(troom.equalsIgnoreCase("Single Room"))
														{
															type_of_room = 150;
														}
																									
														
												 double type_of_bed = 0; 														
														if(bed.equalsIgnoreCase("Single"))
														{
															type_of_bed = type_of_room * 4/100;
														}
														else if(bed.equalsIgnoreCase("Double"))
														{
															type_of_bed = type_of_room * 5/100;
														}
														else if(bed.equalsIgnoreCase("Triple"))
														{
															type_of_bed = type_of_room * 6/100;
														}
														else if(bed.equalsIgnoreCase("Quad"))
														{
															type_of_bed = type_of_room * 7/100;
														}
														else if(bed.equalsIgnoreCase("None"))
														{
															type_of_bed = type_of_room * 0/100;
														}
														
												 double type_of_meal = 0; 																												
														if(meal.equalsIgnoreCase("Room only"))
														{
															type_of_meal=type_of_bed * 0;
														}
														else if(meal.equalsIgnoreCase("Breakfast"))
														{
															type_of_meal=type_of_bed * 4;
														}else if(meal.equalsIgnoreCase("Half Board"))
														{
															type_of_meal=type_of_bed * 5;
														
														}else if(meal.equalsIgnoreCase("Full Board"))
														{
															type_of_meal=type_of_bed * 6;
														}
														
														
														double ttot = type_of_room * days * nroom;
														double mepr = type_of_meal * days;
														double btot = type_of_bed *days;
														
														double fintot = ttot + mepr + btot ;
															
															//"<script type='text/javascript'> alert('count_date')</script>";
														String psql = "INSERT INTO payment(id, title, fname, lname, troom, tbed, nroom, cin, cout, ttot,meal, mepr, btot,fnumberot,noofdays) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
														ps=c.prepareStatement(psql);
														ps.setInt(1,id);ps.setString(2,title);ps.setString(3,fname);ps.setString(4,lname);ps.setString(5,troom);ps.setString(6,bed);
														ps.setInt(7,nroom);ps.setString(8,cin);ps.setString(9,cout);ps.setDouble(10,ttot);ps.setString(11,meal);ps.setDouble(12,mepr);ps.setDouble(13,btot);
														ps.setDouble(14,fintot);ps.setInt(15,days);
								
														int i1=ps.executeUpdate();
														if(i1>0)
														{	String notfree="NotFree";
															String rpsql = "UPDATE room SET place='"+notfree+"',cusid="+id+" where bedding ='"+bed+"' and type='"+troom+"' ";
															ps=c.prepareStatement(rpsql);
															int i2=ps.executeUpdate();
															if(i2>0)
															{	response.sendRedirect("home.jsp");
															
      out.write("\r\n");
      out.write("																<script type='text/javascript'> alert('Booking Confirm');</script>\r\n");
      out.write("																<script type='text/javascript'> window.location='home.jsp'</script>\r\n");
      out.write("															");
}
															
															
														}
												
											}
									
                                        
							}	
					
						}
					
									
									
							
						
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
