/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.97
 * Generated at: 2024-12-18 02:15:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.*;
import java.sql.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


	public static String getDate()
	{	
		DateFormat df=new SimpleDateFormat("yyyy-MMM-dd");
		String date=df.format(new java.util.Date());
		return date;
	}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/user/Desktop/backend/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hotel/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153377882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1734448720554L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

	Connection c=(Connection)application.getAttribute("connection");
	PreparedStatement ps;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>SUNRISE HOTEL</title>\r\n");
      out.write("<!-- for-mobile-apps -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"Resort Inn Responsive , Smartphone Compatible web template , Samsung, LG, Sony Ericsson, Motorola web design\" />\r\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false);\r\n");
      out.write("		function hideURLbar(){ window.scrollTo(0,1); } </script>\r\n");
      out.write("<!-- //for-mobile-apps -->\r\n");
      out.write("<link href=\"css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<link href=\"css/font-awesome.css\" rel=\"stylesheet\"> \r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/chocolat.css\" type=\"text/css\" media=\"screen\">\r\n");
      out.write("<link href=\"css/easy-responsive-tabs.css\" rel='stylesheet' type='text/css'/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/flexslider.css\" type=\"text/css\" media=\"screen\" property=\"\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/jquery-ui.css\" />\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/modernizr-2.6.2.min.js\"></script>\r\n");
      out.write("<!--fonts-->\r\n");
      out.write("<link href=\"//fonts.googleapis.com/css?family=Oswald:300,400,700\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"//fonts.googleapis.com/css?family=Federo\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"//fonts.googleapis.com/css?family=Lato:300,400,700,900\" rel=\"stylesheet\">\r\n");
      out.write("<!--//fonts-->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- header -->\r\n");
      out.write("<div class=\"banner-top\">\r\n");
      out.write("			<div class=\"social-bnr-agileits\">\r\n");
      out.write("				<ul class=\"social-icons3\">\r\n");
      out.write("								<li><a href=\"https://www.facebook.com/\" class=\"fa fa-facebook icon-border facebook\"> </a></li>\r\n");
      out.write("								<li><a href=\"https://twitter.com/\" class=\"fa fa-twitter icon-border twitter\"> </a></li>\r\n");
      out.write("								<li><a href=\"https://plus.google.com/u/0/\" class=\"fa fa-google-plus icon-border googleplus\"> </a></li> \r\n");
      out.write("							</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"contact-bnr-w3-agile\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><i class=\"fa fa-envelope\" aria-hidden=\"true\"></i><a href=\"mailto:info@example.com\">INFO@SUNRISE.COM</a></li>\r\n");
      out.write("					<li><i class=\"fa fa-phone\" aria-hidden=\"true\"></i>+91 95222-44-554</li>	\r\n");
      out.write("				<li><i class=\"\" aria-hidden=\"true\"></i><a href=\"admin/index.jsp\" class=\"btn btn-primary\"><b>Login</b></a></li>\r\n");
      out.write("				\r\n");
      out.write("					<li class=\"s-bar\">\r\n");
      out.write("						<div class=\"search\">\r\n");
      out.write("							<a href ='searchHotels.jsp'> search hotel </a>\r\n");
      out.write("							</span></label>\r\n");
      out.write("							\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"clearfix\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("	<div class=\"w3_navigation\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<nav class=\"navbar navbar-default\">\r\n");
      out.write("				<div class=\"navbar-header navbar-left\">\r\n");
      out.write("					<button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("						<span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("						<span class=\"icon-bar\"></span>\r\n");
      out.write("						<span class=\"icon-bar\"></span>\r\n");
      out.write("						<span class=\"icon-bar\"></span>\r\n");
      out.write("					</button>\r\n");
      out.write("					<h1><a class=\"navbar-brand\" href=\"index.jsp\">SUN <span>RISE</span><p class=\"logo_w3l_agile_caption\">Your Dreamy Resort</p></a></h1>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("				<div class=\"collapse navbar-collapse navbar-right\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("					<nav class=\"menu menu--iris\">\r\n");
      out.write("						<ul class=\"nav navbar-nav menu__list\">\r\n");
      out.write("							<li class=\"menu__item menu__item--current\"><a href=\"index.html\" class=\"menu__link\">Home</a></li>\r\n");
      out.write("							<li class=\"menu__item\"><a href=\"#about\" class=\"menu__link scroll\">About</a></li>\r\n");
      out.write("							<li class=\"menu__item\"><a href=\"#team\" class=\"menu__link scroll\">Team</a></li>\r\n");
      out.write("							<li class=\"menu__item\"><a href=\"#gallery\" class=\"menu__link scroll\">Gallery</a></li>\r\n");
      out.write("							<li class=\"menu__item\"><a href=\"#rooms\" class=\"menu__link scroll\">Rooms</a></li>\r\n");
      out.write("							<li class=\"menu__item\"><a href=\"#contact\" class=\"menu__link scroll\">Contact Us</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</nav>\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("<!-- //header -->\r\n");
      out.write("		<!-- banner -->\r\n");
      out.write("	<div id=\"home\" class=\"w3ls-banner\">\r\n");
      out.write("		<!-- banner-text -->\r\n");
      out.write("		<div class=\"slider\">\r\n");
      out.write("			<div class=\"callbacks_container\">\r\n");
      out.write("				<ul class=\"rslides callbacks callbacks1\" id=\"slider4\">\r\n");
      out.write("					<li>\r\n");
      out.write("						<div class=\"w3layouts-banner-top\">\r\n");
      out.write("\r\n");
      out.write("							<div class=\"container\">\r\n");
      out.write("								<div class=\"agileits-banner-info\">\r\n");
      out.write("								<h4>SUN RISE</h4>\r\n");
      out.write("									<h3>We know what you love</h3>\r\n");
      out.write("										<p>Welcome to our hotels</p>\r\n");
      out.write("									<div class=\"agileits_w3layouts_more menu__item\">\r\n");
      out.write("				<a href=\"#\" class=\"menu__link\" data-toggle=\"modal\" data-target=\"#myModal\">Learn More</a>\r\n");
      out.write("			</div>\r\n");
      out.write("								</div>	\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<div class=\"w3layouts-banner-top w3layouts-banner-top1\">\r\n");
      out.write("							<div class=\"container\">\r\n");
      out.write("								<div class=\"agileits-banner-info\">\r\n");
      out.write("								<h4>SUN RISE</h4>\r\n");
      out.write("									<h3>Stay with friends & families</h3>\r\n");
      out.write("										<p>Come & enjoy precious moment with us</p>\r\n");
      out.write("									<div class=\"agileits_w3layouts_more menu__item\">\r\n");
      out.write("				<a href=\"#\" class=\"menu__link\" data-toggle=\"modal\" data-target=\"#myModal\">Learn More</a>\r\n");
      out.write("			</div>\r\n");
      out.write("								</div>	\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<div class=\"w3layouts-banner-top w3layouts-banner-top2\">\r\n");
      out.write("							<div class=\"container\">\r\n");
      out.write("								<div class=\"agileits-banner-info\">\r\n");
      out.write("								<h4>SUN RISE</h4>\r\n");
      out.write("								<h3>want luxurious vacation?</h3>\r\n");
      out.write("										<p>Get accommodation today</p>\r\n");
      out.write("									<div class=\"agileits_w3layouts_more menu__item\">\r\n");
      out.write("											<a href=\"#\" class=\"menu__link\" data-toggle=\"modal\" data-target=\"#myModal\">Learn More</a>\r\n");
      out.write("										</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"clearfix\"> </div>\r\n");
      out.write("			<!--banner Slider starts Here-->\r\n");
      out.write("		</div>\r\n");
      out.write("		    <div class=\"thim-click-to-bottom\">\r\n");
      out.write("				<a href=\"#about\" class=\"scroll\">\r\n");
      out.write("					<i class=\"fa fa-long-arrow-down\" aria-hidden=\"true\"></i>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("	</div>	\r\n");
      out.write("	<!-- //banner --> \r\n");
      out.write("<!--//Header-->\r\n");
      out.write("<!-- //Modal1 -->\r\n");
      out.write("<div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("						<!-- Modal1 -->\r\n");
      out.write("							<div class=\"modal-dialog\">\r\n");
      out.write("							<!-- Modal content-->\r\n");
      out.write("								<div class=\"modal-content\">\r\n");
      out.write("									<div class=\"modal-header\">\r\n");
      out.write("										<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("										<h4>SUN  <span>RISE</span></h4>\r\n");
      out.write("										<img src=\"images/1.jpg\" alt=\" \" class=\"img-responsive\">\r\n");
      out.write("										<h5>We know what you love</h5>\r\n");
      out.write("										<p>Providing guests unique and enchanting views from their rooms with its exceptional amenities, makes Star Hotel one of bests in its kind.Try our food menu, awesome services and friendly staff while you are here.</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("<!-- //Modal1 -->\r\n");
      out.write("<div id=\"availability-agileits\">\r\n");
      out.write("<div class=\"col-md-12 book-form-left-w3layouts\">\r\n");
      out.write("	<a href=\"admin/reservation.jsp\"><h2>ROOM RESERVATION</h2></a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"clearfix\"> </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- banner-bottom -->\r\n");
      out.write("	<div class=\"banner-bottom\">\r\n");
      out.write("		<div class=\"container\">	\r\n");
      out.write("			<div class=\"agileits_banner_bottom\">\r\n");
      out.write("				<h3><span>Experience a good stay, enjoy fantastic offers</span> Find our friendly welcoming reception</h3>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"w3ls_banner_bottom_grids\">\r\n");
      out.write("				<ul class=\"cbp-ig-grid\">\r\n");
      out.write("					<li>\r\n");
      out.write("						<div class=\"w3_grid_effect\">\r\n");
      out.write("							<span class=\"cbp-ig-icon w3_road\"></span>\r\n");
      out.write("							<h4 class=\"cbp-ig-title\">MASTER BEDROOMS</h4>\r\n");
      out.write("							<span class=\"cbp-ig-category\">SUN RISE</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<div class=\"w3_grid_effect\">\r\n");
      out.write("							<span class=\"cbp-ig-icon w3_cube\"></span>\r\n");
      out.write("							<h4 class=\"cbp-ig-title\">SEA VIEW BALCONY</h4>\r\n");
      out.write("							<span class=\"cbp-ig-category\">SUN RISE</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<div class=\"w3_grid_effect\">\r\n");
      out.write("							<span class=\"cbp-ig-icon w3_users\"></span>\r\n");
      out.write("							<h4 class=\"cbp-ig-title\">LARGE CAFE</h4>\r\n");
      out.write("							<span class=\"cbp-ig-category\">SUN RISE</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<div class=\"w3_grid_effect\">\r\n");
      out.write("							<span class=\"cbp-ig-icon w3_ticket\"></span>\r\n");
      out.write("							<h4 class=\"cbp-ig-title\">WIFI COVERAGE</h4>\r\n");
      out.write("							<span class=\"cbp-ig-category\">SUN RISE</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("<!-- //banner-bottom -->\r\n");
      out.write("<!-- /about -->\r\n");
      out.write(" 	<div class=\"about-wthree\" id=\"about\">\r\n");
      out.write("		  <div class=\"container\">\r\n");
      out.write("				   <div class=\"ab-w3l-spa\">\r\n");
      out.write("                            <h3 class=\"title-w3-agileits title-black-wthree\">About Our SUN RISE</h3> \r\n");
      out.write("						   <p class=\"about-para-w3ls\">Permits the clients globally to reserve the rooms in the hotel at any time. It will provide a unique search and book functionally for the customers anywhere in the world. This project can be used by the clients and the travel agencies who will help them to reserve the hotel of their choice. Sometimes people face problem in reserving the hotels in the places where they want to visit. In that situation, this project can be of great relief to them. The user interface must be simple and easy to understand even by the common man.</p>\r\n");
      out.write("						   <img src=\"images/about.jpg\" class=\"img-responsive\" alt=\"Hair Salon\">\r\n");
      out.write("										<div class=\"w3l-slider-img\">\r\n");
      out.write("											<img src=\"images/a1.jpg\" class=\"img-responsive\" alt=\"Hair Salon\">\r\n");
      out.write("										</div>\r\n");
      out.write("                                       <div class=\"w3ls-info-about\">\r\n");
      out.write("										    <h4>You'll love all the amenities we offer!</h4>\r\n");
      out.write("											<p>100% Sure that you will love it. </p>\r\n");
      out.write("										</div>\r\n");
      out.write("		          </div>\r\n");
      out.write("		   	<div class=\"clearfix\"> </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write(" 	<!-- //about -->\r\n");
      out.write("<!--sevices-->\r\n");
      out.write("<div class=\"advantages\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"advantages-main\">\r\n");
      out.write("				<h3 class=\"title-w3-agileits\">Our Services</h3>\r\n");
      out.write("		   <div class=\"advantage-bottom\">\r\n");
      out.write("			 <div class=\"col-md-6 advantage-grid left-w3ls wow bounceInLeft\" data-wow-delay=\"0.3s\">\r\n");
      out.write("			 	<div class=\"advantage-block \">\r\n");
      out.write("					<i class=\"fa fa-credit-card\" aria-hidden=\"true\"></i>\r\n");
      out.write("			 		<h4>Stay First, Pay After! </h4>\r\n");
      out.write("			 		<p>We have the very new and exclusive facility of Pay Later. Pay later facility has some term and conditions. Please do notice.</p>\r\n");
      out.write("					<p><i class=\"fa fa-check\" aria-hidden=\"true\"></i>Decorated room, proper air conditioned</p>\r\n");
      out.write("					<p><i class=\"fa fa-check\" aria-hidden=\"true\"></i>Private balcony</p>\r\n");
      out.write("			 		\r\n");
      out.write("			 	</div>\r\n");
      out.write("			 </div>\r\n");
      out.write("			 <div class=\"col-md-6 advantage-grid right-w3ls wow zoomIn\" data-wow-delay=\"0.3s\">\r\n");
      out.write("			 	<div class=\"advantage-block\">\r\n");
      out.write("					<i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i>\r\n");
      out.write("			 		<h4>24 Hour Restaurant</h4>\r\n");
      out.write("			 		<p>We are providing 24 hours of service without any question. Ask for service and you will be offered with no any single question.</p>\r\n");
      out.write("					<p><i class=\"fa fa-check\" aria-hidden=\"true\"></i>24 hours room service</p>\r\n");
      out.write("					<p><i class=\"fa fa-check\" aria-hidden=\"true\"></i>24-hour Concierge service</p>\r\n");
      out.write("			 	</div>\r\n");
      out.write("			 </div>\r\n");
      out.write("			<div class=\"clearfix\"> </div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--//sevices-->\r\n");
      out.write("<!-- team -->\r\n");
      out.write("<div class=\"team\" id=\"team\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("			<h3 class=\"title-w3-agileits title-black-wthree\">Meet Our Team</h3>\r\n");
      out.write("			<div id=\"horizontalTab\">\r\n");
      out.write("					<ul class=\"resp-tabs-list\">\r\n");
      out.write("					<li>\r\n");
      out.write("						<img src=\"images/teams1.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<img src=\"images/teams2.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<img src=\"images/teams3.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<img src=\"images/teams4.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("					</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<div class=\"resp-tabs-container\">\r\n");
      out.write("					<div class=\"tab1\">\r\n");
      out.write("						<div class=\"col-md-6 team-img-w3-agile\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-6 team-Info-agileits\">\r\n");
      out.write("							<h4>Lucas Jimenez</h4>\r\n");
      out.write("							<span>Manager</span>\r\n");
      out.write("							<p>He is Responsible for managing employees and for planning, marketing , coordinating and administering hotel services such as catering and accommodation facilities.</p>\r\n");
      out.write("						<div class=\"social-bnr-agileits footer-icons-agileinfo\">\r\n");
      out.write("							<ul class=\"social-icons3\">\r\n");
      out.write("								<li><a href=\"#\" class=\"fa fa-facebook icon-border facebook\"> </a></li>\r\n");
      out.write("								<li><a href=\"#\" class=\"fa fa-twitter icon-border twitter\"> </a></li>\r\n");
      out.write("								<li><a href=\"#\" class=\"fa fa-google-plus icon-border googleplus\"> </a></li> \r\n");
      out.write("								<li><a href=\"#\" class=\"fa fa-rss icon-border rss\"> </a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>							\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"clearfix\"> </div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"tab2\">\r\n");
      out.write("					<div class=\"col-md-6 team-img-w3-agile\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-6 team-Info-agileits\">\r\n");
      out.write("							<h4>Sarah Connor</h4>\r\n");
      out.write("							<span>Receptionist</span>\r\n");
      out.write("							<p>Serves visitors by greeting, welcoming, and directing them appropriately.Maintains security and telecommunications system.Informs visitors by answering or referring inquiries.Keeps a safe and clean reception area by complying with procedures, rules, and regulations.</p>	\r\n");
      out.write("						<div class=\"social-bnr-agileits footer-icons-agileinfo\">\r\n");
      out.write("							<ul class=\"social-icons3\">\r\n");
      out.write("								<li><a href=\"#\" class=\"fa fa-facebook icon-border facebook\"> </a></li>\r\n");
      out.write("								<li><a href=\"#\" class=\"fa fa-twitter icon-border twitter\"> </a></li>\r\n");
      out.write("								<li><a href=\"#\" class=\"fa fa-google-plus icon-border googleplus\"> </a></li> \r\n");
      out.write("								<li><a href=\"#\" class=\"fa fa-rss icon-border rss\"> </a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>							\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"clearfix\"> </div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"tab3\">\r\n");
      out.write("						<div class=\"col-md-6 team-img-w3-agile\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-6 team-Info-agileits\">\r\n");
      out.write("							<h4>Ivan Simpson</h4>\r\n");
      out.write("							<span>Manager</span>\r\n");
      out.write("							<p>He is Responsible for managing employees and for planning, marketing , coordinating and administering hotel services such as catering and accommodation facilities.</p>\r\n");
      out.write("						<div class=\"social-bnr-agileits footer-icons-agileinfo\">\r\n");
      out.write("							<ul class=\"social-icons3\">\r\n");
      out.write("								<li><a href=\"#\" class=\"fa fa-facebook icon-border facebook\"> </a></li>\r\n");
      out.write("								<li><a href=\"#\" class=\"fa fa-twitter icon-border twitter\"> </a></li>\r\n");
      out.write("								<li><a href=\"#\" class=\"fa fa-google-plus icon-border googleplus\"> </a></li> \r\n");
      out.write("								<li><a href=\"#\" class=\"fa fa-rss icon-border rss\"> </a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>							\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"clearfix\"> </div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"tab4\">\r\n");
      out.write("					<div class=\"col-md-6 team-img-w3-agile\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-6 team-Info-agileits\">\r\n");
      out.write("							<h4>Marc Gutierrez</h4>\r\n");
      out.write("							<span>Receptionist</span>\r\n");
      out.write("							<p>Serves visitors by greeting, welcoming, and directing them appropriately.Maintains security and telecommunications system.Informs visitors by answering or referring inquiries.Keeps a safe and clean reception area by complying with procedures, rules, and regulations.</p>	\r\n");
      out.write("						<div class=\"social-bnr-agileits footer-icons-agileinfo\">\r\n");
      out.write("							<ul class=\"social-icons3\">\r\n");
      out.write("								<li><a href=\"#\" class=\"fa fa-facebook icon-border facebook\"> </a></li>\r\n");
      out.write("								<li><a href=\"#\" class=\"fa fa-twitter icon-border twitter\"> </a></li>\r\n");
      out.write("								<li><a href=\"#\" class=\"fa fa-google-plus icon-border googleplus\"> </a></li> \r\n");
      out.write("								<li><a href=\"#\" class=\"fa fa-rss icon-border rss\"> </a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>							\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"clearfix\"> </div>\r\n");
      out.write("					</div>\r\n");
      out.write("					</div>\r\n");
      out.write("			</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //team -->\r\n");
      out.write("<!-- Gallery -->\r\n");
      out.write("<section class=\"portfolio-w3ls\" id=\"gallery\">\r\n");
      out.write("		 <h3 class=\"title-w3-agileits title-black-wthree\">Our Gallery</h3>\r\n");
      out.write("				<div class=\"col-md-3 gallery-grid gallery1\">\r\n");
      out.write("					<a href=\"images/g1.jpg\" class=\"swipebox\"><img src=\"images/g1.jpg\" class=\"img-responsive\" alt=\"/\">\r\n");
      out.write("						<div class=\"textbox\">\r\n");
      out.write("						<h4>SUN RISE</h4>\r\n");
      out.write("							<p><i class=\"fa fa-picture-o\" aria-hidden=\"true\"></i></p>\r\n");
      out.write("						</div>\r\n");
      out.write("				</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3 gallery-grid gallery1\">\r\n");
      out.write("					<a href=\"images/g2.jpg\" class=\"swipebox\"><img src=\"images/g2.jpg\" class=\"img-responsive\" alt=\"/\">\r\n");
      out.write("						<div class=\"textbox\">\r\n");
      out.write("						<h4>SUN RISE</h4>\r\n");
      out.write("							<p><i class=\"fa fa-picture-o\" aria-hidden=\"true\"></i></p>\r\n");
      out.write("						</div>\r\n");
      out.write("				</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3 gallery-grid gallery1\">\r\n");
      out.write("					<a href=\"images/g3.jpg\" class=\"swipebox\"><img src=\"images/g3.jpg\" class=\"img-responsive\" alt=\"/\">\r\n");
      out.write("						<div class=\"textbox\">\r\n");
      out.write("						<h4>SUN RISE</h4>\r\n");
      out.write("							<p><i class=\"fa fa-picture-o\" aria-hidden=\"true\"></i></p>\r\n");
      out.write("						</div>\r\n");
      out.write("				</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3 gallery-grid gallery1\">\r\n");
      out.write("					<a href=\"images/g4.jpg\" class=\"swipebox\"><img src=\"images/g4.jpg\" class=\"img-responsive\" alt=\"/\">\r\n");
      out.write("						<div class=\"textbox\">\r\n");
      out.write("						<h4>SUN RISE</h4>\r\n");
      out.write("							<p><i class=\"fa fa-picture-o\" aria-hidden=\"true\"></i></p>\r\n");
      out.write("						</div>\r\n");
      out.write("				</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3 gallery-grid gallery1\">\r\n");
      out.write("					<a href=\"images/g5.jpg\" class=\"swipebox\"><img src=\"images/g5.jpg\" class=\"img-responsive\" alt=\"/\">\r\n");
      out.write("						<div class=\"textbox\">\r\n");
      out.write("						<h4>SUN RISE</h4>\r\n");
      out.write("							<p><i class=\"fa fa-picture-o\" aria-hidden=\"true\"></i></p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3 gallery-grid gallery1\">\r\n");
      out.write("					<a href=\"images/g6.jpg\" class=\"swipebox\"><img src=\"images/g6.jpg\" class=\"img-responsive\" alt=\"/\">\r\n");
      out.write("						<div class=\"textbox\">\r\n");
      out.write("						<h4>SUN RISE</h4>\r\n");
      out.write("							<p><i class=\"fa fa-picture-o\" aria-hidden=\"true\"></i></p>\r\n");
      out.write("					   </div>\r\n");
      out.write("				   </a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3 gallery-grid gallery1\">\r\n");
      out.write("					<a href=\"images/g6.jpg\" class=\"swipebox\"><img src=\"images/g7.jpg\" class=\"img-responsive\" alt=\"/\">\r\n");
      out.write("						<div class=\"textbox\">\r\n");
      out.write("						<h4>SUN RISE</h4>\r\n");
      out.write("							<p><i class=\"fa fa-picture-o\" aria-hidden=\"true\"></i></p>\r\n");
      out.write("					   </div>\r\n");
      out.write("				   </a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3 gallery-grid gallery1\">\r\n");
      out.write("					<a href=\"images/g6.jpg\" class=\"swipebox\"><img src=\"images/g8.jpg\" class=\"img-responsive\" alt=\"/\">\r\n");
      out.write("						<div class=\"textbox\">\r\n");
      out.write("						<h4>SUN RISE</h4>\r\n");
      out.write("							<p><i class=\"fa fa-picture-o\" aria-hidden=\"true\"></i></p>\r\n");
      out.write("					   </div>\r\n");
      out.write("				   </a>\r\n");
      out.write("				</div>\r\n");
      out.write("					<div class=\"col-md-3 gallery-grid gallery1\">\r\n");
      out.write("					<a href=\"images/g9.jpg\" class=\"swipebox\"><img src=\"images/g9.jpg\" class=\"img-responsive\" alt=\"/\">\r\n");
      out.write("						<div class=\"textbox\">\r\n");
      out.write("						<h4>SUN RISE</h4>\r\n");
      out.write("							<p><i class=\"fa fa-picture-o\" aria-hidden=\"true\"></i></p>\r\n");
      out.write("						</div>\r\n");
      out.write("				</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3 gallery-grid gallery1\">\r\n");
      out.write("					<a href=\"images/g10.jpg\" class=\"swipebox\"><img src=\"images/g10.jpg\" class=\"img-responsive\" alt=\"/\">\r\n");
      out.write("						<div class=\"textbox\">\r\n");
      out.write("						<h4>SUN RISE</h4>\r\n");
      out.write("							<p><i class=\"fa fa-picture-o\" aria-hidden=\"true\"></i></p>\r\n");
      out.write("						</div>\r\n");
      out.write("				</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3 gallery-grid gallery1\">\r\n");
      out.write("					<a href=\"images/g4.jpg\" class=\"swipebox\"><img src=\"images/g4.jpg\" class=\"img-responsive\" alt=\"/\">\r\n");
      out.write("						<div class=\"textbox\">\r\n");
      out.write("						<h4>SUN RISE</h4>\r\n");
      out.write("							<p><i class=\"fa fa-picture-o\" aria-hidden=\"true\"></i></p>\r\n");
      out.write("						</div>\r\n");
      out.write("				</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3 gallery-grid gallery1\">\r\n");
      out.write("					<a href=\"images/g2.jpg\" class=\"swipebox\"><img src=\"images/g2.jpg\" class=\"img-responsive\" alt=\"/\">\r\n");
      out.write("						<div class=\"textbox\">\r\n");
      out.write("						<h4>SUN RISE</h4>\r\n");
      out.write("							<p><i class=\"fa fa-picture-o\" aria-hidden=\"true\"></i></p>\r\n");
      out.write("						</div>\r\n");
      out.write("				</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"clearfix\"> </div>\r\n");
      out.write("</section>\r\n");
      out.write("<!-- //gallery -->\r\n");
      out.write("	 <!-- rooms & rates -->\r\n");
      out.write("      <div class=\"plans-section\" id=\"rooms\">\r\n");
      out.write("				 <div class=\"container\">\r\n");
      out.write("				 <h3 class=\"title-w3-agileits title-black-wthree\">Rooms And Rates</h3>\r\n");
      out.write("						<div class=\"priceing-table-main\">\r\n");
      out.write("				 <div class=\"col-md-3 price-grid\">\r\n");
      out.write("					<div class=\"price-block agile\">\r\n");
      out.write("						<div class=\"price-gd-top\">\r\n");
      out.write("						<img src=\"images/r1.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("							<h4>Deluxe Room</h4>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"price-gd-bottom\">\r\n");
      out.write("							   <div class=\"price-list\">\r\n");
      out.write("									<ul>\r\n");
      out.write("											<li><i class=\"fa fa-star\" aria-hidden=\"true\"></i></li>\r\n");
      out.write("											<li><i class=\"fa fa-star\" aria-hidden=\"true\"></i></li>\r\n");
      out.write("											<li><i class=\"fa fa-star\" aria-hidden=\"true\"></i></li>\r\n");
      out.write("											<li><i class=\"fa fa-star\" aria-hidden=\"true\"></i></li>\r\n");
      out.write("											<li><i class=\"fa fa-star-o\" aria-hidden=\"true\"></i></li>\r\n");
      out.write("									\r\n");
      out.write("								     </ul>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"price-selet\">	\r\n");
      out.write("								<h3><span>Rs.</span>320</h3>						\r\n");
      out.write("								<a href=\"admin/reservation.jsp\" >Book Now</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3 price-grid \">\r\n");
      out.write("					<div class=\"price-block agile\">\r\n");
      out.write("						<div class=\"price-gd-top\">\r\n");
      out.write("						<img src=\"images/r2.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("							<h4>Luxury Room</h4>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"price-gd-bottom\">\r\n");
      out.write("							<div class=\"price-list\">\r\n");
      out.write("									<ul>\r\n");
      out.write("									<li><i class=\"fa fa-star\" aria-hidden=\"true\"></i></li>\r\n");
      out.write("									<li><i class=\"fa fa-star\" aria-hidden=\"true\"></i></li>\r\n");
      out.write("									<li><i class=\"fa fa-star\" aria-hidden=\"true\"></i></li>\r\n");
      out.write("									<li><i class=\"fa fa-star\" aria-hidden=\"true\"></i></li>\r\n");
      out.write("									<li><i class=\"fa fa-star-o\" aria-hidden=\"true\"></i></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"price-selet\">\r\n");
      out.write("								<h3><span>Rs.</span>220</h3>\r\n");
      out.write("								<a href=\"admin/reservation.jsp\" >Book Now</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3 price-grid lost\">\r\n");
      out.write("					<div class=\"price-block agile\">\r\n");
      out.write("						<div class=\"price-gd-top\">\r\n");
      out.write("						<img src=\"images/r3.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("							<h4>Guest House</h4>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"price-gd-bottom\">\r\n");
      out.write("							<div class=\"price-list\">\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><i class=\"fa fa-star\" aria-hidden=\"true\"></i></li>\r\n");
      out.write("									<li><i class=\"fa fa-star\" aria-hidden=\"true\"></i></li>\r\n");
      out.write("									<li><i class=\"fa fa-star\" aria-hidden=\"true\"></i></li>\r\n");
      out.write("									<li><i class=\"fa fa-star-o\" aria-hidden=\"true\"></i></li>\r\n");
      out.write("									<li><i class=\"fa fa-star-o\" aria-hidden=\"true\"></i></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"price-selet\">\r\n");
      out.write("								<h3><span>Rs.</span>180</h3>\r\n");
      out.write("								<a href=\"admin/reservation.jsp\" >Book Now</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3 price-grid wthree lost\">\r\n");
      out.write("					<div class=\"price-block agile\">\r\n");
      out.write("						<div class=\"price-gd-top \">\r\n");
      out.write("							<img src=\"images/r4.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("							<h4>Single Room</h4>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"price-gd-bottom\">\r\n");
      out.write("							<div class=\"price-list\">\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><i class=\"fa fa-star\" aria-hidden=\"true\"></i></li>\r\n");
      out.write("									<li><i class=\"fa fa-star\" aria-hidden=\"true\"></i></li>\r\n");
      out.write("									<li><i class=\"fa fa-star-o\" aria-hidden=\"true\"></i></li>\r\n");
      out.write("									<li><i class=\"fa fa-star-o\" aria-hidden=\"true\"></i></li>\r\n");
      out.write("									<li><i class=\"fa fa-star-o\" aria-hidden=\"true\"></i></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"price-selet\">\r\n");
      out.write("								<h3><span>Rs.</span> 150</h3>\r\n");
      out.write("								<a href=\"admin/reservation.jsp\" >Book Now</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"clearfix\"> </div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	 <!--// rooms & rates -->\r\n");
      out.write("  <!-- visitors -->\r\n");
      out.write("	<div class=\"w3l-visitors-agile\" >\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("                 <h3 class=\"title-w3-agileits title-black-wthree\">What other visitors experienced</h3> \r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"w3layouts_work_grids\">\r\n");
      out.write("			<section class=\"slider\">\r\n");
      out.write("				<div class=\"flexslider\">\r\n");
      out.write("					<ul class=\"slides\">\r\n");
      out.write("						<li>\r\n");
      out.write("							<div class=\"w3layouts_work_grid_left\">\r\n");
      out.write("								<img src=\"images/5.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("								<div class=\"w3layouts_work_grid_left_pos\">\r\n");
      out.write("									<img src=\"images/c1.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"w3layouts_work_grid_right\">\r\n");
      out.write("								<h4>\r\n");
      out.write("								<i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("								<i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("								<i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("								<i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("								<i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("								Worth to come again\r\n");
      out.write("								</h4>\r\n");
      out.write("								<p>Fabulous five-star service in a five-minute timeframe. \r\n");
      out.write("									very good system to pre-register the guest online. \r\n");
      out.write("									visitor gets a temporary wi-fi password. visitors look and feel their best. Thats why I loved it.</p>\r\n");
      out.write("								<h5>Julia Rose</h5>\r\n");
      out.write("								<p>Germany</p>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"clearfix\"> </div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<div class=\"w3layouts_work_grid_left\">\r\n");
      out.write("								<img src=\"images/5.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("								<div class=\"w3layouts_work_grid_left_pos\">\r\n");
      out.write("									<img src=\"images/c2.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"w3layouts_work_grid_right\">\r\n");
      out.write("								<h4>\r\n");
      out.write("								<i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("								<i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("								<i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("								<i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("								<i class=\"fa fa-star-o\" aria-hidden=\"true\"></i>\r\n");
      out.write("								Worth to come again\r\n");
      out.write("								</h4>\r\n");
      out.write("								<p>Fabulous five-star service in a five-minute timeframe. \r\n");
      out.write("									very good system to pre-register the guest online. \r\n");
      out.write("									visitor gets a temporary wi-fi password. visitors look and feel their best. Thats why I loved it.</p>\r\n");
      out.write("								<h5>Jahnatan Smith</h5>\r\n");
      out.write("								<p>United States</p>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"clearfix\"> </div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<div class=\"w3layouts_work_grid_left\">\r\n");
      out.write("								<img src=\"images/5.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("								<div class=\"w3layouts_work_grid_left_pos\">\r\n");
      out.write("									<img src=\"images/c3.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"w3layouts_work_grid_right\">\r\n");
      out.write("								<h4>\r\n");
      out.write("								<i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("								<i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("								<i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("								<i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("								<i class=\"fa fa-star-o\" aria-hidden=\"true\"></i>\r\n");
      out.write("								Worth to come again\r\n");
      out.write("								</h4>\r\n");
      out.write("								<p>Fabulous five-star service in a five-minute timeframe. \r\n");
      out.write("									very good system to pre-register the guest online. \r\n");
      out.write("									visitor gets a temporary wi-fi password. visitors look and feel their best. Thats why I loved it.</p>\r\n");
      out.write("								<h5>Rosalind Cloer</h5>\r\n");
      out.write("								<p>Italy</p>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"clearfix\"> </div>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<div class=\"w3layouts_work_grid_left\">\r\n");
      out.write("								<img src=\"images/5.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("								<div class=\"w3layouts_work_grid_left_pos\">\r\n");
      out.write("									<img src=\"images/c4.jpg\" alt=\" \" class=\"img-responsive\" />\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"w3layouts_work_grid_right\">\r\n");
      out.write("								<h4>\r\n");
      out.write("								<i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("								<i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("								<i class=\"fa fa-star\" aria-hidden=\"true\"></i>\r\n");
      out.write("								<i class=\"fa fa-star-o\" aria-hidden=\"true\"></i>\r\n");
      out.write("								<i class=\"fa fa-star-o\" aria-hidden=\"true\"></i>\r\n");
      out.write("								Worth to come again\r\n");
      out.write("								</h4>\r\n");
      out.write("								<p>Fabulous five-star service in a five-minute timeframe. \r\n");
      out.write("									very good system to pre-register the guest online. \r\n");
      out.write("									visitor gets a temporary wi-fi password. visitors look and feel their best. Thats why I loved it.</p>\r\n");
      out.write("								<h5>Amie Bublitz</h5>\r\n");
      out.write("								<p>Switzerland</p>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"clearfix\"> </div>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</section>\r\n");
      out.write("		</div>	\r\n");
      out.write("	</div>\r\n");
      out.write("  <!-- visitors -->\r\n");
      out.write("<!-- contact -->\r\n");
      out.write("<section class=\"contact-w3ls\" id=\"contact\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"col-lg-6 col-md-6 col-sm-6 contact-w3-agile2\" data-aos=\"flip-left\">\r\n");
      out.write("			<div class=\"contact-agileits\">\r\n");
      out.write("				<h4>Contact Us</h4>\r\n");
      out.write("				<p class=\"contact-agile2\">Sign Up For Our News Letters</p>\r\n");
      out.write("				<form  method=\"post\" name=\"sentMessage\" id=\"contactForm\" action=\"index.jsp\">\r\n");
      out.write("					<div class=\"control-group form-group\">\r\n");
      out.write("                        \r\n");
      out.write("                            <label class=\"contact-p1\">Full Name:</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" name=\"name\" id=\"name\" required >\r\n");
      out.write("                            <p class=\"help-block\"></p>\r\n");
      out.write("                       \r\n");
      out.write("                    </div>	\r\n");
      out.write("                    <div class=\"control-group form-group\">\r\n");
      out.write("                        \r\n");
      out.write("                            <label class=\"contact-p1\">Phone Number:</label>\r\n");
      out.write("                            <input type=\"tel\" class=\"form-control\" name=\"phone\" id=\"phone\" required >\r\n");
      out.write("							<p class=\"help-block\"></p>\r\n");
      out.write("						\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"control-group form-group\">\r\n");
      out.write("                        \r\n");
      out.write("                            <label class=\"contact-p1\">Email Address:</label>\r\n");
      out.write("                            <input type=\"email\" class=\"form-control\" name=\"email\" id=\"email\" required >\r\n");
      out.write("							<p class=\"help-block\"></p>\r\n");
      out.write("						\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    <input type=\"submit\" name=\"sub\" value=\"Send Now\" class=\"btn btn-primary\">	\r\n");
      out.write("				</form>\r\n");
      out.write("				");

				if(request.getParameter("sub")!=null)
				{
					String name =request.getParameter("name");
					long phone = Long.parseLong(request.getParameter("phone").trim());
					String email = request.getParameter("email");
					String approval = "Not Allowed";
					String curDate=getDate();
					String q = "INSERT INTO contact(name, phoneno, email,cdate,approval) VALUES (?,?,?,?,?)" ;
					ps=c.prepareStatement(q);
					ps.setString(1,name);ps.setLong(2,phone);ps.setString(3,email);ps.setString(4,curDate);ps.setString(5,approval);
					
					int i=ps.executeUpdate();
					if(i>0){
						out.print("OK");
      out.write("\r\n");
      out.write("						<script type='text/javascript'> alert(\"You Have Sign Up for Newsletter successfully.\")</script>\r\n");
      out.write("					");
}
					
				}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-lg-6 col-md-6 col-sm-6 contact-w3-agile1\" data-aos=\"flip-right\">\r\n");
      out.write("			<h4>Connect With Us</h4>\r\n");
      out.write("			<p class=\"contact-agile1\"><strong>Phone :</strong>+91 (95)222-44-554</p>\r\n");
      out.write("			<p class=\"contact-agile1\"><strong>Email :</strong> <a href=\"mailto:name@example.com\">INFO@SUNRISE.COM</a></p>\r\n");
      out.write("			<p class=\"contact-agile1\"><strong>Address :</strong> New Kalmunai Road, Mathura, India</p>\r\n");
      out.write("																\r\n");
      out.write("			<div class=\"social-bnr-agileits footer-icons-agileinfo\">\r\n");
      out.write("				<ul class=\"social-icons3\">\r\n");
      out.write("								<li><a href=\"#\" class=\"fa fa-facebook icon-border facebook\"> </a></li>\r\n");
      out.write("								<li><a href=\"#\" class=\"fa fa-twitter icon-border twitter\"> </a></li>\r\n");
      out.write("								<li><a href=\"#\" class=\"fa fa-google-plus icon-border googleplus\"> </a></li> \r\n");
      out.write("								\r\n");
      out.write("							</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3074.7905052320443!2d-77.84987248482734!3d39.586871613613056!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c9f6a80ccf0661%3A0x7210426c67abc40!2sVirginia+Welcome+Center%2FSafety+Rest+Area!5e0!3m2!1sen!2sin!4v1485760915662\" ></iframe>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"clearfix\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("</section>\r\n");
      out.write("<!-- /contact -->\r\n");
      out.write("			<div class=\"copy\">\r\n");
      out.write("		        <p>  2020-2021 SUNRISE . All Rights Reserved | Design by <a href=\"index.jsp\">SUNRISE</a> </p>\r\n");
      out.write("		    </div>\r\n");
      out.write("<!--/footer -->\r\n");
      out.write("<!-- js -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-2.1.4.min.js\"></script>\r\n");
      out.write("<!-- contact form -->\r\n");
      out.write("<script src=\"js/jqBootstrapValidation.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- /contact form -->	\r\n");
      out.write("<!-- Calendar -->\r\n");
      out.write("		<script src=\"js/jquery-ui.js\"></script>\r\n");
      out.write("		<script>\r\n");
      out.write("				$(function() {\r\n");
      out.write("				$( \"#datepicker,#datepicker1,#datepicker2,#datepicker3\" ).datepicker();\r\n");
      out.write("				});\r\n");
      out.write("		</script>\r\n");
      out.write("<!-- //Calendar -->\r\n");
      out.write("<!-- gallery popup -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/swipebox.css\">\r\n");
      out.write("				<script src=\"js/jquery.swipebox.min.js\"></script> \r\n");
      out.write("					<script type=\"text/javascript\">\r\n");
      out.write("						jQuery(function($) {\r\n");
      out.write("							$(\".swipebox\").swipebox();\r\n");
      out.write("						});\r\n");
      out.write("					</script>\r\n");
      out.write("<!-- //gallery popup -->\r\n");
      out.write("<!-- start-smoth-scrolling -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/move-top.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/easing.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	jQuery(document).ready(function($) {\r\n");
      out.write("		$(\".scroll\").click(function(event){		\r\n");
      out.write("			event.preventDefault();\r\n");
      out.write("			$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- start-smoth-scrolling -->\r\n");
      out.write("<!-- flexSlider -->\r\n");
      out.write("				<script defer src=\"js/jquery.flexslider.js\"></script>\r\n");
      out.write("				<script type=\"text/javascript\">\r\n");
      out.write("				$(window).load(function(){\r\n");
      out.write("				  $('.flexslider').flexslider({\r\n");
      out.write("					animation: \"slide\",\r\n");
      out.write("					start: function(slider){\r\n");
      out.write("					  $('body').removeClass('loading');\r\n");
      out.write("					}\r\n");
      out.write("				  });\r\n");
      out.write("				});\r\n");
      out.write("			  </script>\r\n");
      out.write("			<!-- //flexSlider -->\r\n");
      out.write("<script src=\"js/responsiveslides.min.js\"></script>\r\n");
      out.write("			<script>\r\n");
      out.write("						// You can also use \"$(window).load(function() {\"\r\n");
      out.write("						$(function () {\r\n");
      out.write("						  // Slideshow 4\r\n");
      out.write("						  $(\"#slider4\").responsiveSlides({\r\n");
      out.write("							auto: true,\r\n");
      out.write("							pager:true,\r\n");
      out.write("							nav:false,\r\n");
      out.write("							speed: 500,\r\n");
      out.write("							namespace: \"callbacks\",\r\n");
      out.write("							before: function () {\r\n");
      out.write("							  $('.events').append(\"<li>before event fired.</li>\");\r\n");
      out.write("							},\r\n");
      out.write("							after: function () {\r\n");
      out.write("							  $('.events').append(\"<li>after event fired.</li>\");\r\n");
      out.write("							}\r\n");
      out.write("						  });\r\n");
      out.write("					\r\n");
      out.write("						});\r\n");
      out.write("			</script>\r\n");
      out.write("		<!--search-bar-->\r\n");
      out.write("		<script src=\"js/main.js\"></script>	\r\n");
      out.write("<!--//search-bar-->\r\n");
      out.write("<!--tabs-->\r\n");
      out.write("<script src=\"js/easy-responsive-tabs.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function () {\r\n");
      out.write("$('#horizontalTab').easyResponsiveTabs({\r\n");
      out.write("type: 'default', //Types: default, vertical, accordion           \r\n");
      out.write("width: 'auto', //auto or any width like 600px\r\n");
      out.write("fit: true,   // 100% fit in a container\r\n");
      out.write("closed: 'accordion', // Start closed if in accordion view\r\n");
      out.write("activate: function(event) { // Callback function if tab is switched\r\n");
      out.write("var $tab = $(this);\r\n");
      out.write("var $info = $('#tabInfo');\r\n");
      out.write("var $name = $('span', $info);\r\n");
      out.write("$name.text($tab.text());\r\n");
      out.write("$info.show();\r\n");
      out.write("}\r\n");
      out.write("});\r\n");
      out.write("$('#verticalTab').easyResponsiveTabs({\r\n");
      out.write("type: 'vertical',\r\n");
      out.write("width: 'auto',\r\n");
      out.write("fit: true\r\n");
      out.write("});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<!--//tabs-->\r\n");
      out.write("<!-- smooth scrolling -->\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		$(document).ready(function() {\r\n");
      out.write("		/*\r\n");
      out.write("			var defaults = {\r\n");
      out.write("			containerID: 'toTop', // fading element id\r\n");
      out.write("			containerHoverID: 'toTopHover', // fading element hover id\r\n");
      out.write("			scrollSpeed: 1200,\r\n");
      out.write("			easingType: 'linear' \r\n");
      out.write("			};\r\n");
      out.write("		*/								\r\n");
      out.write("		$().UItoTop({ easingType: 'easeOutQuart' });\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"arr-w3ls\">\r\n");
      out.write("	<a href=\"#home\" id=\"toTop\" style=\"display: block;\"> <span id=\"toTopHover\" style=\"opacity: 1;\"> </span></a>\r\n");
      out.write("	</div>\r\n");
      out.write("<!-- //smooth scrolling -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/bootstrap-3.1.1.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
